name: CD to Docker Hub

# on:
#   create:
#     tags:
#       - "v*.*.*"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make mvnw executable
        run: cd inotes && cd webserver && chmod +x mvnw

      - name: Build packages and install them
        run: cd inotes && cd webserver && ./mvnw clean install -B --no-transfer-progress

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./inotes/webserver/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/swengass2:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} 